Support for Astronomy units
usnistgov/OpenSeadragonScalebar pull request #5
Opened 2017-02-15 19:42 UTC by youngmd

Astronomers typically use units of arcsecond, arcminute, and degree to define distances between points on the sky.  This change adds an ASTRONOMY option to the ScalebarSizeAndTextRenderer that handles and displays these values with the correct units when pixelsPerMeter is set to correct value of pixels per arcsecond (inverse of the pixelscale) in the original image.

2017-02-16 08:15 UTC, avandecreme commented
Thanks for the contribution! I will try to review this when I have some time.
Could you post a screenshot here?

2017-02-17 17:11 UTC, youngmd commented
<img width="790" alt="astro_scalebar1" src="https://cloud.githubusercontent.com/assets/1247513/23075335/067d56f2-f50a-11e6-89f7-11702d76e308.png">
<img width="692" alt="astro_scalebar2" src="https://cloud.githubusercontent.com/assets/1247513/23075336/06903b1e-f50a-11e6-9eaf-cbe9c8869ddd.png">

Here's a couple, the first showing a zoomed out region with the scalebar showing 2' ( the ' symbol indicates arcminutes), and zoomed in showing 20" (the " indicates arcseconds).

2017-02-18 08:11 UTC, avandecreme requested changes
Thanks for the screenshots! It looks good to me, I have a few minors comments.

2017-02-18 08:11 UTC, avandecreme commented on openseadragon-scalebar.js
> +	    var maxSize = minSize * 2;
Please add one indentation space.

2017-02-18 08:11 UTC, avandecreme commented on openseadragon-scalebar.js
> +	    },
Please remove 3 spaces.

2017-02-18 08:11 UTC, avandecreme commented on openseadragon-scalebar.js
> +    function getScalebarSizeAndText(ppm, minSize, unitSuffix, handlePlural, spacer = ' ') {
I would rather not use this syntax for compatibility with older browsers.
Could you remove the `= ' '` here and add `spacer = spacer === undefined ? ' ' : spacer;` on the next line?

2017-02-27 16:03 UTC, youngmd commented on openseadragon-scalebar.js
> +	    var maxSize = minSize * 2;
Confused about this one.  Spacing looks fine in my commit (4 spaces in) but this is showing 3...

2017-02-28 08:34 UTC, avandecreme commented on openseadragon-scalebar.js
> +	    var maxSize = minSize * 2;
Right, it looks good here: https://github.com/youngmd/OpenSeadragonScalebar/blob/ce5e0abbd8d4b5a80be8edbdfc8c7078801245fc/openseadragon-scalebar.js
Must be a github bug.

2017-02-28 08:35 UTC, merged

2017-02-28 08:35 UTC, avandecreme commented
Thanks for doing and sharing this!